In [65]:
import pandas as pd

df = pd.read_csv("SpotifyData.csv")
df

,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo,valence,year
0,0.9950,['Carl Woitschach'],0.708,158648,0.1950,0,6KbQ3uYMLKb5jDxLF7wYDD,0.563000,10,0.1510,-12.428,1,Singende Bataillone 1. Teil,0,1928,0.0506,118.469,0.7790,1928
1,0.9940,"['Robert Schumann', 'Vladimir Horowitz']",0.379,282133,0.0135,0,6KuQTIu1KoTTkLXKrwlLPV,0.901000,8,0.0763,-28.454,1,"Fantasiestücke, Op. 111: Più tosto lento",0,1928,0.0462,83.972,0.0767,1928
2,0.6040,['Seweryn Goszczyński'],0.749,104300,0.2200,0,6L63VW0PibdM1HDSBoqnoM,0.000000,5,0.1190,-19.924,0,Chapter 1.18 - Zamek kaniowski,0,1928,0.9290,107.177,0.8800,1928
3,0.9950,['Francisco Canaro'],0.781,180760,0.1300,0,6M94FkXd15sOAOQYRnWPN8,0.887000,1,0.1110,-14.734,0,Bebamos Juntos - Instrumental (Remasterizado),0,1928-09-25,0.0926,108.003,0.7200,1928
4,0.9900,"['Frédéric Chopin', 'Vladimir Horowitz']",0.210,687733,0.2040,0,6N6tiFZ9vLTSOIxkj8qKrd,0.908000,11,0.0980,-16.829,1,"Polonaise-Fantaisie in A-Flat Major, Op. 61",1,1928,0.0424,62.149,0.0693,1928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169904,0.1730,"['DripReport', 'Tyga']",0.875,163800,0.4430,1,4KppkflX7I3vJQk7urOJaS,0.000032,1,0.0891,-7.461,1,Skechers (feat. Tyga) - Remix,75,2020-05-15,0.1430,100.012,0.3060,2020
169905,0.0167,"['Leon Bridges', 'Terrace Martin']",0.719,167468,0.3850,0,1ehhGlTvjtHo2e4xJFB0SZ,0.031300,8,0.1110,-10.907,1,Sweeter (feat. Terrace Martin),64,2020-06-08,0.0403,128.000,0.2700,2020
169906,0.5380,"['Kygo', 'Oh Wonder']",0.514,180700,0.5390,0,52eycxprLhK3lPcRLbQiVk,0.002330,7,0.1080,-9.332,1,How Would I Know,70,2020-05-29,0.1050,123.700,0.1530,2020
169907,0.0714,"['Cash Cash', 'Andy Grammer']",0.646,167308,0.7610,0,3wYOGJYD31sLRmBgCvWxa4,0.000000,1,0.2220,-2.557,1,I Found You,70,2020-02-28,0.0385,129.916,0.4720,2020
169908,0.1090,['Ingrid Andress'],0.512,214787,0.4280,0,60RFlt48hm0l4Fu0JoccOl,0.000000,0,0.1050,-7.387,1,More Hearts Than Mine,65,2020-03-27,0.0271,80.588,0.3660,2020

In [46]:
# Dropping columns for variables not considered.

col = ['acousticness', 'speechiness', 'valence', 'tempo', 'duration_ms', 'release_date', 'year']
df1 = df[col]
df1

,acousticness,speechiness,valence,tempo,duration_ms,release_date,year
0,0.9950,0.0506,0.7790,118.469,158648,1928,1928
1,0.9940,0.0462,0.0767,83.972,282133,1928,1928
2,0.6040,0.9290,0.8800,107.177,104300,1928,1928
3,0.9950,0.0926,0.7200,108.003,180760,1928-09-25,1928
4,0.9900,0.0424,0.0693,62.149,687733,1928,1928
...,...,...,...,...,...,...,...
169904,0.1730,0.1430,0.3060,100.012,163800,2020-05-15,2020
169905,0.0167,0.0403,0.2700,128.000,167468,2020-06-08,2020
169906,0.5380,0.1050,0.1530,123.700,180700,2020-05-29,2020
169907,0.0714,0.0385,0.4720,129.916,167308,2020-02-28,2020
169908,0.1090,0.0271,0.3660,80.588,214787,2020-03-27,2020

In [66]:
# Filtering and removing rows to limit to releases in the last 40 years (1980-2020).

df2 = df1[(df1["year"] > 1979)]
df2

,acousticness,speechiness,valence,tempo,duration_ms,release_date,year
4054,0.00439,0.1280,0.780,171.362,215213,1980-10-17,1980
4055,0.18000,0.0294,0.635,82.626,246800,1980-01-01,1980
4056,0.48300,0.0292,0.960,101.289,256240,1980,1980
4057,0.00187,0.0304,0.636,167.032,267573,1980,1980
4058,0.13200,0.0465,0.978,123.480,247160,1980-10-08,1980
...,...,...,...,...,...,...,...
169904,0.17300,0.1430,0.306,100.012,163800,2020-05-15,2020
169905,0.01670,0.0403,0.270,128.000,167468,2020-06-08,2020
169906,0.53800,0.1050,0.153,123.700,180700,2020-05-29,2020
169907,0.07140,0.0385,0.472,129.916,167308,2020-02-28,2020
169908,0.10900,0.0271,0.366,80.588,214787,2020-03-27,2020

In [48]:
df2.to_csv("clean_data.csv", index=False)
df2

,acousticness,speechiness,valence,tempo,duration_ms,release_date,year
4054,0.00439,0.1280,0.780,171.362,215213,1980-10-17,1980
4055,0.18000,0.0294,0.635,82.626,246800,1980-01-01,1980
4056,0.48300,0.0292,0.960,101.289,256240,1980,1980
4057,0.00187,0.0304,0.636,167.032,267573,1980,1980
4058,0.13200,0.0465,0.978,123.480,247160,1980-10-08,1980
...,...,...,...,...,...,...,...
169904,0.17300,0.1430,0.306,100.012,163800,2020-05-15,2020
169905,0.01670,0.0403,0.270,128.000,167468,2020-06-08,2020
169906,0.53800,0.1050,0.153,123.700,180700,2020-05-29,2020
169907,0.07140,0.0385,0.472,129.916,167308,2020-02-28,2020
169908,0.10900,0.0271,0.366,80.588,214787,2020-03-27,2020

In [49]:
df3 = pd.read_csv("clean_data.csv")
df3

,acousticness,speechiness,valence,tempo,duration_ms,release_date,year
0,0.00439,0.1280,0.780,171.362,215213,1980-10-17,1980
1,0.18000,0.0294,0.635,82.626,246800,1980-01-01,1980
2,0.48300,0.0292,0.960,101.289,256240,1980,1980
3,0.00187,0.0304,0.636,167.032,267573,1980,1980
4,0.13200,0.0465,0.978,123.480,247160,1980-10-08,1980
...,...,...,...,...,...,...,...
81651,0.17300,0.1430,0.306,100.012,163800,2020-05-15,2020
81652,0.01670,0.0403,0.270,128.000,167468,2020-06-08,2020
81653,0.53800,0.1050,0.153,123.700,180700,2020-05-29,2020
81654,0.07140,0.0385,0.472,129.916,167308,2020-02-28,2020
81655,0.10900,0.0271,0.366,80.588,214787,2020-03-27,2020

In [50]:
print(df3['release_date'].dtype)

object

In [51]:
# Removing rows without a month indicated in the release_date column.

df3['release_date'] = df3['release_date'].astype(str)
df3 = df3.loc[df3['release_date'].str.len () == 10]
df3

,acousticness,speechiness,valence,tempo,duration_ms,release_date,year
0,0.00439,0.1280,0.780,171.362,215213,1980-10-17,1980
1,0.18000,0.0294,0.635,82.626,246800,1980-01-01,1980
4,0.13200,0.0465,0.978,123.480,247160,1980-10-08,1980
6,0.03230,0.0261,0.513,119.571,319133,1980-06-01,1980
7,0.00935,0.1000,0.740,198.651,268733,1980-04-26,1980
...,...,...,...,...,...,...,...
81651,0.17300,0.1430,0.306,100.012,163800,2020-05-15,2020
81652,0.01670,0.0403,0.270,128.000,167468,2020-06-08,2020
81653,0.53800,0.1050,0.153,123.700,180700,2020-05-29,2020
81654,0.07140,0.0385,0.472,129.916,167308,2020-02-28,2020
81655,0.10900,0.0271,0.366,80.588,214787,2020-03-27,2020

In [52]:
df3.to_csv("clean_data2.csv", index=False)
df3

,acousticness,speechiness,valence,tempo,duration_ms,release_date,year
0,0.00439,0.1280,0.780,171.362,215213,1980-10-17,1980
1,0.18000,0.0294,0.635,82.626,246800,1980-01-01,1980
4,0.13200,0.0465,0.978,123.480,247160,1980-10-08,1980
6,0.03230,0.0261,0.513,119.571,319133,1980-06-01,1980
7,0.00935,0.1000,0.740,198.651,268733,1980-04-26,1980
...,...,...,...,...,...,...,...
81651,0.17300,0.1430,0.306,100.012,163800,2020-05-15,2020
81652,0.01670,0.0403,0.270,128.000,167468,2020-06-08,2020
81653,0.53800,0.1050,0.153,123.700,180700,2020-05-29,2020
81654,0.07140,0.0385,0.472,129.916,167308,2020-02-28,2020
81655,0.10900,0.0271,0.366,80.588,214787,2020-03-27,2020

In [53]:
df4 = pd.read_csv("clean_data2.csv")
df4

,acousticness,speechiness,valence,tempo,duration_ms,release_date,year
0,0.00439,0.1280,0.780,171.362,215213,1980-10-17,1980
1,0.18000,0.0294,0.635,82.626,246800,1980-01-01,1980
2,0.13200,0.0465,0.978,123.480,247160,1980-10-08,1980
3,0.03230,0.0261,0.513,119.571,319133,1980-06-01,1980
4,0.00935,0.1000,0.740,198.651,268733,1980-04-26,1980
...,...,...,...,...,...,...,...
68364,0.17300,0.1430,0.306,100.012,163800,2020-05-15,2020
68365,0.01670,0.0403,0.270,128.000,167468,2020-06-08,2020
68366,0.53800,0.1050,0.153,123.700,180700,2020-05-29,2020
68367,0.07140,0.0385,0.472,129.916,167308,2020-02-28,2020
68368,0.10900,0.0271,0.366,80.588,214787,2020-03-27,2020

In [54]:
# Create new column with just the month (taken from release_date) and cosmetic fix to duration column title 
# and changing back data type for release_date.

df4['month'] = df4['release_date'].str[5:7]
df4['month'] = df4['month'].astype(int)
df4['release_date'] = df4['release_date'].astype(object)
df4

,acousticness,speechiness,valence,tempo,duration_ms,release_date,year,month
0,0.00439,0.1280,0.780,171.362,215213,1980-10-17,1980,10
1,0.18000,0.0294,0.635,82.626,246800,1980-01-01,1980,1
2,0.13200,0.0465,0.978,123.480,247160,1980-10-08,1980,10
3,0.03230,0.0261,0.513,119.571,319133,1980-06-01,1980,6
4,0.00935,0.1000,0.740,198.651,268733,1980-04-26,1980,4
...,...,...,...,...,...,...,...,...
68364,0.17300,0.1430,0.306,100.012,163800,2020-05-15,2020,5
68365,0.01670,0.0403,0.270,128.000,167468,2020-06-08,2020,6
68366,0.53800,0.1050,0.153,123.700,180700,2020-05-29,2020,5
68367,0.07140,0.0385,0.472,129.916,167308,2020-02-28,2020,2
68368,0.10900,0.0271,0.366,80.588,214787,2020-03-27,2020,3

In [61]:
df4.to_csv("cleaned_data.csv", index=False)
df4

,acousticness,speechiness,valence,tempo,duration_ms,release_date,year,month
0,0.00439,0.1280,0.780,171.362,215213,1980-10-17,1980,10
1,0.18000,0.0294,0.635,82.626,246800,1980-01-01,1980,1
2,0.13200,0.0465,0.978,123.480,247160,1980-10-08,1980,10
3,0.03230,0.0261,0.513,119.571,319133,1980-06-01,1980,6
4,0.00935,0.1000,0.740,198.651,268733,1980-04-26,1980,4
...,...,...,...,...,...,...,...,...
68364,0.17300,0.1430,0.306,100.012,163800,2020-05-15,2020,5
68365,0.01670,0.0403,0.270,128.000,167468,2020-06-08,2020,6
68366,0.53800,0.1050,0.153,123.700,180700,2020-05-29,2020,5
68367,0.07140,0.0385,0.472,129.916,167308,2020-02-28,2020,2
68368,0.10900,0.0271,0.366,80.588,214787,2020-03-27,2020,3

In [62]:
df5 = pd.read_csv("cleaned_data.csv")
df5

,acousticness,speechiness,valence,tempo,duration_ms,release_date,year,month
0,0.00439,0.1280,0.780,171.362,215213,1980-10-17,1980,10
1,0.18000,0.0294,0.635,82.626,246800,1980-01-01,1980,1
2,0.13200,0.0465,0.978,123.480,247160,1980-10-08,1980,10
3,0.03230,0.0261,0.513,119.571,319133,1980-06-01,1980,6
4,0.00935,0.1000,0.740,198.651,268733,1980-04-26,1980,4
...,...,...,...,...,...,...,...,...
68364,0.17300,0.1430,0.306,100.012,163800,2020-05-15,2020,5
68365,0.01670,0.0403,0.270,128.000,167468,2020-06-08,2020,6
68366,0.53800,0.1050,0.153,123.700,180700,2020-05-29,2020,5
68367,0.07140,0.0385,0.472,129.916,167308,2020-02-28,2020,2
68368,0.10900,0.0271,0.366,80.588,214787,2020-03-27,2020,3

In [67]:
# Getting averages of features by month and year.

avg_extrap = df5.groupby(['year', 'month']).agg(
    avg_acousticness = ('acousticness', 'mean'),
    avg_duration = ('duration_ms', 'mean'),
    avg_speechiness = ('speechiness', 'mean'),
    avg_valence = ('valence', 'mean'),
    avg_tempo = ('tempo', 'mean')
)
print(avg_extrap)

            avg_acousticness   avg_duration  avg_speechiness  avg_valence  \
year month
1980 1              0.434264  268339.939759         0.059292     0.565335
     2              0.209261  229122.986486         0.052231     0.648446
     3              0.186878  243819.898734         0.058167     0.513268
     4              0.269994  236968.148649         0.065803     0.609665
     5              0.286761  258279.706522         0.049707     0.714957
...                      ...            ...              ...          ...
2020 2              0.263531  192486.093750         0.137242     0.490281
     3              0.225235  198767.352349         0.143809     0.477247
     4              0.270292  191430.562290         0.146991     0.497826
     5              0.215873  193162.245940         0.157803     0.477182
     6              0.253392  208825.003175         0.126343     0.502239

             avg_tempo
year month
1980 1      119.476096
     2      128.684932
     3      127.424266
     4      122.250824
     5      125.674467
...                ...
2020 2      120.638156
     3      124.392792
     4      119.401118
     5      123.115534
     6      119.786546

[486 rows x 5 columns]

In [64]:
avg_extrap.to_csv("averages_year_month.csv")
avg_extrap

            avg_acousticness   avg_duration  avg_speechiness  avg_valence  \
year month
1980 1              0.434264  268339.939759         0.059292     0.565335
     2              0.209261  229122.986486         0.052231     0.648446
     3              0.186878  243819.898734         0.058167     0.513268
     4              0.269994  236968.148649         0.065803     0.609665
     5              0.286761  258279.706522         0.049707     0.714957
...                      ...            ...              ...          ...
2020 2              0.263531  192486.093750         0.137242     0.490281
     3              0.225235  198767.352349         0.143809     0.477247
     4              0.270292  191430.562290         0.146991     0.497826
     5              0.215873  193162.245940         0.157803     0.477182
     6              0.253392  208825.003175         0.126343     0.502239

             avg_tempo
year month
1980 1      119.476096
     2      128.684932
     3      127.424266
     4      122.250824
     5      125.674467
...                ...
2020 2      120.638156
     3      124.392792
     4      119.401118
     5      123.115534
     6      119.786546

[486 rows x 5 columns]